name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Init
      run: terraform init
    - name: Validation
      run: terraform validate
    - name: Terraform Compliance Tests
      run: |
        echo "[jnonino]" > ~/.aws/credentials
        echo "aws_access_key_id = TEST_ACCESS" >> ~/.aws/credentials
        echo "aws_secret_access_key = TEST_SECRET" >> ~/.aws/credentials
        make terraform-compliance
